### List all messages
GET http://localhost:3000/messages

### Create a new message
POST http://localhost:3000/messages
content-type: application/json

{
  "content": "Teste Segunda Feira do Rest"
}

### List a single messages by Id
GET http://localhost:3000/messages/99999